// This file is generated by [oats][0] and should not be edited by hand.
//
// [0]: https://github.com/influxdata/oats

export type PinnedItemArray = PinnedItem[]

export interface PinnedItem {
  id?: string
  orgID?: string
  type?: string
  userID?: string
  createdAt?: string
  updatedAt?: string
  metadata?: any
}

export interface Error {
  /** code is the machine-readable error code. */
  readonly code:
    | 'internal error'
    | 'not found'
    | 'conflict'
    | 'invalid'
    | 'unprocessable entity'
    | 'empty value'
    | 'unavailable'
    | 'forbidden'
    | 'too many requests'
    | 'unauthorized'
    | 'method not allowed'
    | 'request too large'
    | 'unsupported media type'
  /** Human-readable message. */
  readonly message?: string
  /** Describes the logical code operation when the error occurred. Useful for debugging. */
  readonly op?: string
  /** Stack of errors that occurred during processing of the request. Useful for debugging. */
  readonly err?: string
}

interface RequestOptions {
  signal?: AbortSignal
}

export type RequestHandler = (
  url: string,
  query: string,
  init: RequestInit
) => {url: string; query: string; init: RequestInit}
export type ResponseHandler = (
  status: number,
  headers: Headers,
  data: any
) => {status: number; headers: Headers; data: any}

const RequestContext = function (
  requestHandler: RequestHandler,
  responseHandler: ResponseHandler
) {
  this.requestHandler = requestHandler
  this.responseHandler = responseHandler
}

RequestContext.prototype.request = async function (
  method: string,
  url: string,
  params: any = {},
  options: RequestOptions = {}
): Promise<any> {
  const requestHeaders = new Headers(params.headers)
  const contentType = requestHeaders.get('Content-Type') || ''

  if (params.auth) {
    const credentials = btoa(`${params.auth.username}:${params.auth.password}`)

    requestHeaders.append('Authorization', `Basic ${credentials}`)
  }

  const body =
    params.data && contentType.includes('json')
      ? JSON.stringify(params.data)
      : params.data

  const query = params.query ? `?${new URLSearchParams(params.query)}` : ''

  const {
    url: middlewareUrl,
    query: middlewareQuery,
    init,
  } = this.requestHandler(url, query, {
    method,
    body,
    credentials: 'same-origin',
    signal: options.signal,
    headers: requestHeaders,
  })

  const response = await fetch(`${middlewareUrl}${middlewareQuery}`, init)

  const {status, headers} = response
  const responseContentType = headers.get('Content-Type') || ''

  let data

  if (responseContentType.includes('json')) {
    data = await response.json()
  } else if (responseContentType.includes('octet-stream')) {
    data = await response.blob()
  } else {
    data = await response.text()
  }

  return this.responseHandler(status, headers, data)
}

RequestContext.prototype.setRequestHandler = function (
  requestHandler: RequestHandler
) {
  this.requestHandler = requestHandler
}

RequestContext.prototype.setResponseHandler = function (
  responseHandler: ResponseHandler
) {
  this.responseHandler = responseHandler
}

const rc = new RequestContext(
  (url, query, init) => {
    return {url, query, init}
  },
  (status, headers, data) => {
    return {status, headers, data}
  }
)
const request = rc.request.bind(rc)
const setRequestHandler = rc.setRequestHandler.bind(rc)
const setResponseHandler = rc.setResponseHandler.bind(rc)

export {request, setRequestHandler, setResponseHandler}

export interface GetPinnedParams {}

type GetPinnedResult =
  | GetPinnedOKResult
  | GetPinnedUnauthorizedResult
  | GetPinnedInternalServerErrorResult

interface GetPinnedOKResult {
  status: 200
  headers: Headers
  data: PinnedItemArray
}

interface GetPinnedUnauthorizedResult {
  status: 401
  headers: Headers
  data: Error
}

interface GetPinnedInternalServerErrorResult {
  status: 500
  headers: Headers
  data: Error
}

export const getPinned = (
  params: GetPinnedParams,
  options: RequestOptions = {}
): Promise<GetPinnedResult> =>
  request(
    'GET',
    '/api/v2private/pinned',
    params,
    options
  ) as Promise<GetPinnedResult>

export interface PostPinnedParams {
  data?: {
    metadata?: any
    type?: string
  }
}

type PostPinnedResult =
  | PostPinnedOKResult
  | PostPinnedBadRequestResult
  | PostPinnedUnauthorizedResult
  | PostPinnedInternalServerErrorResult

interface PostPinnedOKResult {
  status: 200
  headers: Headers
  data: PinnedItem
}

interface PostPinnedBadRequestResult {
  status: 400
  headers: Headers
  data: Error
}

interface PostPinnedUnauthorizedResult {
  status: 401
  headers: Headers
  data: Error
}

interface PostPinnedInternalServerErrorResult {
  status: 500
  headers: Headers
  data: Error
}

export const postPinned = (
  params: PostPinnedParams,
  options: RequestOptions = {}
): Promise<PostPinnedResult> =>
  request(
    'POST',
    '/api/v2private/pinned',
    {...params, headers: {'Content-Type': 'application/json'}},
    options
  ) as Promise<PostPinnedResult>

export interface PutPinnedParams {
  id: string

  data?: {
    metadata?: any
    type?: string
  }
}

type PutPinnedResult =
  | PutPinnedOKResult
  | PutPinnedBadRequestResult
  | PutPinnedUnauthorizedResult
  | PutPinnedInternalServerErrorResult

interface PutPinnedOKResult {
  status: 200
  headers: Headers
  data: any
}

interface PutPinnedBadRequestResult {
  status: 400
  headers: Headers
  data: Error
}

interface PutPinnedUnauthorizedResult {
  status: 401
  headers: Headers
  data: Error
}

interface PutPinnedInternalServerErrorResult {
  status: 500
  headers: Headers
  data: Error
}

export const putPinned = (
  params: PutPinnedParams,
  options: RequestOptions = {}
): Promise<PutPinnedResult> =>
  request(
    'PUT',
    `/api/v2private/pinned/${params.id}`,
    {...params, headers: {'Content-Type': 'application/json'}},
    options
  ) as Promise<PutPinnedResult>

export interface DeletePinnedParams {
  id: string
}

type DeletePinnedResult =
  | DeletePinnedNoContentResult
  | DeletePinnedBadRequestResult
  | DeletePinnedUnauthorizedResult
  | DeletePinnedNotFoundResult
  | DeletePinnedInternalServerErrorResult

interface DeletePinnedNoContentResult {
  status: 204
  headers: Headers
  data: any
}

interface DeletePinnedBadRequestResult {
  status: 400
  headers: Headers
  data: Error
}

interface DeletePinnedUnauthorizedResult {
  status: 401
  headers: Headers
  data: Error
}

interface DeletePinnedNotFoundResult {
  status: 404
  headers: Headers
  data: Error
}

interface DeletePinnedInternalServerErrorResult {
  status: 500
  headers: Headers
  data: Error
}

export const deletePinned = (
  params: DeletePinnedParams,
  options: RequestOptions = {}
): Promise<DeletePinnedResult> =>
  request(
    'DELETE',
    `/api/v2private/pinned/${params.id}`,
    params,
    options
  ) as Promise<DeletePinnedResult>
